CREATE DATABASE ecommerce_db;

create SCHEMA ecommerce;

CREATE TABLE ecommerce.users (
    user_id     BIGINT PRIMARY KEY,
    first_name  VARCHAR(50) NOT NULL,
    last_name   VARCHAR(50),
    email       VARCHAR(100) UNIQUE NOT NULL,
    phone       VARCHAR(15),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ecommerce.products (
    product_id    BIGINT PRIMARY KEY,
    product_name  VARCHAR(255) NOT NULL,
    price         DECIMAL(10,2) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ecommerce.orders (
    order_id     BIGINT PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    order_status VARCHAR(20) NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    order_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES ecommerce.users(user_id)
);
CREATE TABLE ecommerce.order_items (
    order_item_id BIGINT PRIMARY KEY,
    order_id      BIGINT NOT NULL,
    product_id    BIGINT NOT NULL,
    quantity      INT NOT NULL,
    price         DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE payments (
    payment_id     BIGINT PRIMARY KEY,
    order_id       BIGINT NOT NULL,
    payment_mode   VARCHAR(30),
    payment_status VARCHAR(20),
    paid_amount    DECIMAL(12,2),
    paid_date      TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES ecommerce.orders(order_id)
);



use  ecommerce;
#1.Top 3 Most Sold Products
SELECT p.product_id, p.product_name,SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_sold DESC
LIMIT 3;

#2.Users Who Have Never Placed an Order
SELECT u.user_id,u.email
FROM users u
LEFT JOIN orders o
    ON u.user_id = o.user_id
WHERE o.order_id IS NULL;

#3.Users and their orders
SELECT u.user_id,u.email,o.order_id
FROM users u
LEFT JOIN orders o
    ON u.user_id = o.user_id;
#4.Orders and theirusers 
SELECT   u.user_id,u.email,o.order_id
FROM users u
RIGHT JOIN orders o
    ON u.user_id = o.user_id;
#Total Revenue Generated by Each User
SELECT u.user_id, SUM(o.total_amount) 
FROM users u 
JOIN orders o
    ON  u.user_id=o.user_id  
    GROUP BY u.user_id,u.phone;
    